package br.com.brunoccbertolini.cocktailhelperapp.ui.theme

import androidx.compose.ui.graphics.Color

// Brand palette — a "cocktail" identity: berry primary, citrus/amber secondary, mint tertiary.

// Light
val BerryLight = Color(0xFF9A2143)
val OnBerryLight = Color(0xFFFFFFFF)
val BerryContainerLight = Color(0xFFFFD9DF)
val OnBerryContainerLight = Color(0xFF3F0017)
val CitrusLight = Color(0xFF8A5100)
val OnCitrusLight = Color(0xFFFFFFFF)
val CitrusContainerLight = Color(0xFFFFDCBE)
val OnCitrusContainerLight = Color(0xFF2C1600)
val MintLight = Color(0xFF006B5B)
val OnMintLight = Color(0xFFFFFFFF)
val MintContainerLight = Color(0xFF6FF7DE)
val OnMintContainerLight = Color(0xFF00201A)
val ErrorLight = Color(0xFFBA1A1A)
val OnErrorLight = Color(0xFFFFFFFF)
val ErrorContainerLight = Color(0xFFFFDAD6)
val OnErrorContainerLight = Color(0xFF410002)
val BackgroundLight = Color(0xFFFFFBFF)
val OnBackgroundLight = Color(0xFF201A1B)
val SurfaceLight = Color(0xFFFFFBFF)
val OnSurfaceLight = Color(0xFF201A1B)
val SurfaceVariantLight = Color(0xFFF3DDE0)
val OnSurfaceVariantLight = Color(0xFF524346)
val OutlineLight = Color(0xFF847376)

// Dark
val BerryDark = Color(0xFFFFB2BD)
val OnBerryDark = Color(0xFF5E1130)
val BerryContainerDark = Color(0xFF7C2A47)
val OnBerryContainerDark = Color(0xFFFFD9DF)
val CitrusDark = Color(0xFFFFB870)
val OnCitrusDark = Color(0xFF492900)
val CitrusContainerDark = Color(0xFF693C00)
val OnCitrusContainerDark = Color(0xFFFFDCBE)
val MintDark = Color(0xFF50DBC2)
val OnMintDark = Color(0xFF00382E)
val MintContainerDark = Color(0xFF005144)
val OnMintContainerDark = Color(0xFF6FF7DE)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
val ErrorContainerDark = Color(0xFF93000A)
val OnErrorContainerDark = Color(0xFFFFDAD6)
val BackgroundDark = Color(0xFF201A1B)
val OnBackgroundDark = Color(0xFFECE0E0)
val SurfaceDark = Color(0xFF201A1B)
val OnSurfaceDark = Color(0xFFECE0E0)
val SurfaceVariantDark = Color(0xFF524346)
val OnSurfaceVariantDark = Color(0xFFD6C2C4)
val OutlineDark = Color(0xFF9F8C8F)
